
Harshadasonawane2002/Harshadasonawane2002 is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class operators 
    {
static void Main(string[] args)
{
int a,b,c;
Console.WriteLine("enter 1st no");
a=Convert.ToInt32(Console.ReadLine);
Console.WriteLine("enter 2nd no");
b=Convert.ToInt32(Console.ReadLine);
c=a+b;
Console.WriteLine("addition of no is"+c);
}
}
    }
}
